### ISSUE TITLE
Hi,how to run the staple tracker?

### ISSUE THREAD

**Issue by daiwc** [handsomeleeshu/StapleVisualTracker#1]
Could you give me some ideas to run the tracker on linux or windows?

**Comment by handsomeleeshu** [comment]
if your platform is not arm based, you can simply compile all the .c files except those under folder "arm" with no special C flags(just -c -o should be enough), and then linked all obj files as an shared library. For simply using, you can refer staple.h for information, there are only 4 APIs in it, Staple_Init, Staple_Run, Staple_GetTargetRect and Staple_Destroy. You need transform your rgb frame to stp_multichannel_image struct type, which I believe is not difficult. Sample code will attach later.

**Comment by daiwc** [comment]
Thanks a lot . hoping for your code!

**Comment by daiwc** [comment]
> if your platform is not arm based, you can simply compile all the .c files except those under folder "arm" with no special C flags(just -c -o should be enough), and then linked all obj files as an shared library. For simply using, you can refer staple.h for information, there are only 4 APIs in it, Staple_Init, Staple_Run, Staple_GetTargetRect and Staple_Destroy. You need transform your rgb frame to stp_multichannel_image struct type, which I believe is not difficult. Sample code will attach later.

my platform is based on arm, it means i should include the staple_neon_opt.h in the stp_image.h，and compiled it together?

**Comment by handsomeleeshu** [comment]
> 
> 
> > if your platform is not arm based, you can simply compile all the .c files except those under folder "arm" with no special C flags(just -c -o should be enough), and then linked all obj files as an shared library. For simply using, you can refer staple.h for information, there are only 4 APIs in it, Staple_Init, Staple_Run, Staple_GetTargetRect and Staple_Destroy. You need transform your rgb frame to stp_multichannel_image struct type, which I believe is not difficult. Sample code will attach later.
> 
> my platform is based on arm, it means i should include the staple_neon_opt.h in the stp_image.h，and compiled it together?

Yes, you can refer to Android.mk for compiling flags information

**Comment by daiwc** [comment]
thank you,I have compiled the tracker sucessfully, but the program exit when init feature map. i think my input maybe wrong. the three input image in stp_multichannel_image should be R G B channel independently？



---Original---

**Comment by handsomeleeshu** [comment]
yes, stp_multichannel_image  contains 3 channels stp_image, each contains one color, the pixels in stp_image should be 32 bit wide, so when transfer RGB888 pixels to stp_multichannel_image should deinterleaved the pixels to 3 stp_image lanes, each q = 0,  0 <= value <= 255

**Comment by liuhuaer** [comment]
Hi，handsomeleeshu

In your way, I can't run your code. can you offer sample code？
